"""
Django settings for ANT_News project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))
load_dotenv(os.path.join(BASE_DIR.parent, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-(k8+$bus#tl$=*&5u=ib(-0$0#9rtw^iasn3p$z2%yzx*)3lpr')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,80.225.90.36,72.61.84.199,spor24.net,www.spor24.net').split(',') if h.strip()]

# CSRF settings
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
CSRF_COOKIE_AGE = 31449600  # 1 year
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8001',
    'http://127.0.0.1:8001',
    'http://80.225.90.36',
    'https://72.61.84.199',
    'https://spor24.net',
    'https://www.spor24.net',
]

# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'unfold.contrib.import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sitemaps',
    'haberler.apps.HaberlerConfig',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    'linkcheck',
    'ckeditor',
    'django.forms',
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ANT_News.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'ANT_News' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'haberler.context_processors.global_ads',
            ],
        },
    },
]

WSGI_APPLICATION = 'ANT_News.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Eğer .env dosyasında DATABASE_URL varsa Supabase'e bağlanır, yoksa yerel SQLite'ı kullanır.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{os.path.join(BASE_DIR, 'db.sqlite3')}"
    )
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp/django_cache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # string path
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic ile tüm dosyaların toplanacağı dizin

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = str(BASE_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom authentication backends
AUTHENTICATION_BACKENDS = [
    'haberler.backends.EmailBackend',  # Custom backend for email authentication
    'django.contrib.auth.backends.ModelBackend',  # Default backend as fallback
]

# Email configuration
# For development, you can use console backend to see emails in the console
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# For production, you would use SMTP backend:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.yourdomain.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@yourdomain.com'
# EMAIL_HOST_PASSWORD = 'your-email-password'

# Admin email for notifications
ADMIN_EMAIL = 'admin@antnews.com'
DEFAULT_FROM_EMAIL = 'spor24 <kenanant@gmail.com>'

# Production email settings - uncomment and configure for production use
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kenanant@gmail.com'
EMAIL_HOST_PASSWORD = 'YOUR_APP_PASSWORD_HERE'
# ADMIN_EMAIL = 'admin@yourdomain.com'

# Custom authentication URLs
LOGIN_URL = '/haberler/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Unfold Admin Settings
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Spor24 Yönetim Paneli",
    "SITE_HEADER": "SPOR24 MASTER KONTROL",
    "SITE_SUBHEADER": "Genel Yayın Yönetmeni: Kenan Ant",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/img/spor24_logo4.png",
        "dark": lambda request: "/static/img/spor24_logo4.png",
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/img/spor24_logo4.png",
        "dark": lambda request: "/static/img/spor24_logo4.png",
    },
    "THEME": "dark",
    "DASHBOARD_CALLBACK": "haberler.admin_dashboard.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Hızlı Erişim & Göstergeler",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Kontrol Paneli",
                        "icon": "dashboard",
                        "link": lambda request: reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Canlı Siteyi Gör",
                        "icon": "open_in_new",
                        "link": "https://spor24.net",
                    },
                    {
                        "title": "İzin & Yetki Matrisi",
                        "icon": "verified_user",
                        "link": lambda request: reverse_lazy("permission_matrix"),
                    },
                    {
                        "title": "Kırık Link Denetimi",
                        "icon": "link_off",
                        "link": lambda request: reverse_lazy("linkcheck_report"),
                    },
                ],
            },
            {
                "title": "Haber ve Yayın Masası",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Yayındaki Haberler",
                        "icon": "newspaper",
                        "link": lambda request: reverse_lazy("admin:haberler_haber_changelist"),
                    },
                    {
                        "title": "Bekleyen Bot Haberleri",
                        "icon": "smart_toy",
                        "link": lambda request: reverse_lazy("admin:haberler_bekleyenhaber_changelist"),
                    },
                    {
                        "title": "Yetkili Onay Kuyruğu",
                        "icon": "pending_actions",
                        "link": lambda request: reverse_lazy("admin:haberler_bekleyenyetkilihaberi_changelist"),
                    },
                    {
                        "title": "Sosyal Medya Haberleri",
                        "icon": "share",
                        "link": lambda request: reverse_lazy("admin:haberler_bekleyensosyalmedyahaberi_changelist"),
                    },
                    {
                        "title": "Kategoriler & Branşlar",
                        "icon": "category",
                        "link": lambda request: reverse_lazy("admin:haberler_kategori_changelist"),
                    },
                ],
            },
            {
                "title": "Federasyonlar & Kaynaklar",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "63 Federasyon Portalı",
                        "icon": "corporate_fare",
                        "link": lambda request: reverse_lazy("admin:haberler_federasyonwebsite_changelist"),
                    },
                    {
                        "title": "Tarama & Scraper Logları",
                        "icon": "receipt_long",
                        "link": lambda request: reverse_lazy("admin:haberler_taramalog_changelist"),
                    },
                    {
                        "title": "Scraper Kontrol Merkezi",
                        "icon": "settings_suggest",
                        "link": lambda request: reverse_lazy("scraper_control"),
                    },
                ],
            },
            {
                "title": "Yazarlar & Ekip",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Köşe Yazarları",
                        "icon": "history_edu",
                        "link": lambda request: reverse_lazy("admin:haberler_koseyazari_changelist"),
                    },
                    {
                        "title": "Kullanıcılar & Aboneler",
                        "icon": "group",
                        "link": lambda request: reverse_lazy("admin:auth_user_changelist"),
                    },
                ],
            },
            {
                "title": "Etkileşim & Topluluk",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Anketler (Polls)",
                        "icon": "poll",
                        "link": lambda request: reverse_lazy("admin:haberler_poll_changelist"),
                    },
                    {
                        "title": "Yarışmalar (Quizzes)",
                        "icon": "quiz",
                        "link": lambda request: reverse_lazy("admin:haberler_quiz_changelist"),
                    },
                    {
                        "title": "Reklamlar & Künye",
                        "icon": "campaign",
                        "link": lambda request: reverse_lazy("admin:haberler_reklam_changelist"),
                    },
                ],
            },
        ],
    },
}

# TELEGRAM BİLDİRİM AYARLARI (Antknight Botu)
# TELEGRAM BILDIRIM AYARLARI (Gecersiz bot askiya alindi, yeni bot bekleniyor)
TELEGRAM_CONFIGS = [
    # {
    #     "token": "",
    #     "chat_id": "7310364082"
    # },
    # {
    #     "token": "",
    #     "chat_id": "-1004353749028"
    # }
]

# RASPBERRY PI 4 API GÜVENLİK ANAHTARI
API_SECRET_KEY = 'spor24_pi4_secret_secure_key_256'

# SİTE ADRESİ (Telegram bildirimleri ve diğer servislerde panel linkleri için)
if os.name == 'nt':
    SITE_URL = 'http://192.168.0.2:8000'
    SITE_DOMAIN = '127.0.0.1:8000'
else:
    SITE_URL = 'https://spor24.net'
    SITE_DOMAIN = 'spor24.net'

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Istanbul'

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = 'uploads/'



