# Generated by Django 5.0.6 on 2025-08-31 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('aciklama', models.TextField(blank=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('ozet', models.TextField(max_length=500)),
                ('icerik', models.TextField()),
                ('resim', models.ImageField(blank=True, null=True, upload_to='haberler/')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('yayinlandi', models.BooleanField(default=True)),
                ('anasayfa_haberi', models.BooleanField(default=False)),
                ('manset_haberi', models.BooleanField(default=False)),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haberler', to='haberler.kategori')),
            ],
            options={
                'verbose_name_plural': 'Haberler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
