# Generated by Django 5.0.6 on 2025-09-02 11:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederasyonWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('ana_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('haberler_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('aktif', models.BooleanField(default=True)),
                ('son_tarama', models.DateTimeField(blank=True, null=True)),
                ('haber_listesi_selector', models.CharField(help_text='CSS selector for news list', max_length=200)),
                ('haber_baslik_selector', models.CharField(help_text='CSS selector for news title', max_length=200)),
                ('haber_link_selector', models.CharField(help_text='CSS selector for news link', max_length=200)),
                ('haber_tarih_selector', models.CharField(blank=True, help_text='CSS selector for news date', max_length=200)),
                ('haber_ozet_selector', models.CharField(blank=True, help_text='CSS selector for news summary', max_length=200)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Federasyon Websiteleri',
            },
        ),
        migrations.AddField(
            model_name='haber',
            name='kaynak_url',
            field=models.URLField(blank=True, help_text='Original source URL', null=True),
        ),
        migrations.AddField(
            model_name='haber',
            name='otomatik_eklendi',
            field=models.BooleanField(default=False, help_text='Was this news added automatically?'),
        ),
        migrations.AddField(
            model_name='haber',
            name='federasyon_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haberler.federasyonwebsite'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='federasyon_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haberler.federasyonwebsite'),
        ),
        migrations.AddConstraint(
            model_name='haber',
            constraint=models.UniqueConstraint(condition=models.Q(('kaynak_url__isnull', False)), fields=('kaynak_url',), name='unique_source_url'),
        ),
    ]
