# Generated by Django 5.0.6 on 2025-09-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_federasyonwebsite_haber_kaynak_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='kose_yazisi',
            field=models.BooleanField(default=False, help_text='Köşe yazısı mı?'),
        ),
    ]
