# Generated by Django 5.0.6 on 2025-09-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_haber_kose_yazisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='goruntulenme_sayisi',
            field=models.PositiveIntegerField(default=0, help_text='Haberin görüntülenme sayısı'),
        ),
    ]
