# Generated by Django 5.0.6 on 2025-09-13 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0005_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('onaylandi', models.BooleanField(default=True)),
                ('haber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='haberler.haber')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('haber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.haber')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Favoriler',
                'ordering': ['-olusturma_tarihi'],
                'unique_together': {('kullanici', 'haber')},
            },
        ),
    ]