# Generated by Django 5.0.6 on 2025-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0006_yorum_favori'),
    ]

    operations = [
        migrations.AddField(
            model_name='federasyonwebsite',
            name='son_yeni_haber_zamani',
            field=models.DateTimeField(blank=True, help_text='En son yeni haberin bulunduğu zaman', null=True),
        ),
    ]
