# Generated by Django 5.0.6 on 2025-09-17 17:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0007_federasyonwebsite_son_yeni_haber_zamani'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BekleyenHaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('ozet', models.TextField(max_length=500)),
                ('icerik', models.TextField()),
                ('kaynak_url', models.URLField(help_text='Original source URL')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('onaylandi', models.BooleanField(default=False)),
                ('reddedildi', models.BooleanField(default=False)),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('red_tarihi', models.DateTimeField(blank=True, null=True)),
                ('federasyon_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.federasyonwebsite')),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylanan_haberler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bekleyen Haberler',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
