# Generated by Django 5.0.6 on 2025-09-19 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0008_bekleyenhaber'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='ust_yorum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_yorumlar', to='haberler.yorum'),
        ),
    ]
