# Generated by Django 5.0.6 on 2025-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0009_yorum_ust_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='bekleyenhaber',
            name='haber_tarihi',
            field=models.DateTimeField(blank=True, help_text='Original news publication date', null=True),
        ),
    ]
