# Generated by Django 5.0.6 on 2025-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0010_bekleyenhaber_haber_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
