# Generated by Django 5.0.6 on 2025-09-30 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0011_increase_slug_max_length_to_60'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BekleyenYetkiliHaberi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('ozet', models.TextField(max_length=500)),
                ('icerik', models.TextField()),
                ('kose_yazisi', models.BooleanField(default=False, help_text='Köşe yazısı mı?')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='bekleyen_haberler/')),
                ('olusturma_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('onaylandi', models.BooleanField(default=False)),
                ('reddedildi', models.BooleanField(default=False)),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('red_tarihi', models.DateTimeField(blank=True, null=True)),
                ('red_nedeni', models.TextField(blank=True, help_text='Reddedilme nedeni', null=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.kategori')),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylanan_yetkili_haberleri', to=settings.AUTH_USER_MODEL)),
                ('yazar', models.ForeignKey(help_text='Yetkili kullanıcı', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bekleyen Yetkili Haberleri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
