# Generated by Django 5.0.6 on 2025-10-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0012_bekleyenyetkilihaberi'),
    ]

    operations = [
        migrations.AddField(
            model_name='haber',
            name='haber_tarihi',
            field=models.DateTimeField(blank=True, help_text='Original news publication date', null=True),
        ),
    ]
