# Generated by Django 5.2.7 on 2025-11-11 19:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0013_haber_haber_tarihi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['ad'], 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterField(
            model_name='haber',
            name='icerik',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
