# Generated by Django 5.2.7 on 2025-11-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0014_alter_kategori_options_alter_haber_icerik'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarateSehir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Karate Şehri',
                'verbose_name_plural': 'Karate Şehirleri',
            },
        ),
        migrations.CreateModel(
            name='KarateKulup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Kulüp Adı')),
                ('yetkili', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kulüp Yetkilisi')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kulupler', to='haberler.karatesehir')),
            ],
            options={
                'verbose_name': 'Karate Kulübü',
                'verbose_name_plural': 'Karate Kulüpleri',
            },
        ),
        migrations.CreateModel(
            name='KarateAntrenor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150, verbose_name='Ad Soyad')),
                ('kademe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antrenörlük Kademesi')),
                ('kulup', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bağlı Olduğu Kulüp')),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antrenorler', to='haberler.karatesehir')),
            ],
            options={
                'verbose_name': 'Karate Antrenörü',
                'verbose_name_plural': 'Karate Antrenörleri',
            },
        ),
    ]
