# Generated by Django 5.2.7 on 2025-12-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0015_karatesehir_karatekulup_karateantrenor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karateantrenor',
            name='ad_soyad',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='kademe',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='kulup',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='sehir',
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='adi_soyadi',
            field=models.CharField(default='', max_length=200, verbose_name='Adı Soyadı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='biyografi',
            field=models.TextField(blank=True, null=True, verbose_name='Biyografi'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='bolge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bölge/Şehir'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='antrenorler/', verbose_name='Fotoğraf'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='kariyer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Antrenörlük Kariyeri/Kademe'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='kusak',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kuşak'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='sira_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sıra No'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='verildigi_tarih',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Verildiği Tarih'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='verildigi_yer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Verildiği Yer'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='vize_yili',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vize Yılı'),
        ),
    ]
