# Generated by Django 5.2.7 on 2025-12-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0016_remove_karateantrenor_ad_soyad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='menude_goster',
            field=models.BooleanField(default=True, verbose_name='Menüde Göster'),
        ),
    ]
