# Generated by Django 5.2.7 on 2026-01-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0017_kategori_menude_goster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sporcu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('ad_soyad', models.CharField(max_length=255, verbose_name='Adı Soyadı')),
                ('kemer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kemer')),
                ('kulup', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kulübü')),
                ('dogum_tarihi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Doğum Tarihi')),
                ('iletisim', models.CharField(blank=True, max_length=100, null=True, verbose_name='İletişim')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Sporcu',
                'verbose_name_plural': 'Sporcular',
            },
        ),
    ]
