# Generated by Django 5.2.7 on 2026-06-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0018_sporcu'),
    ]

    operations = [
        migrations.AddField(
            model_name='bekleyenhaber',
            name='kaynak_resim_url',
            field=models.URLField(blank=True, help_text='Original news image URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='federasyonwebsite',
            name='hata_durumu',
            field=models.BooleanField(default=False, help_text='Son tarama hatalı bitti mi?'),
        ),
        migrations.AddField(
            model_name='federasyonwebsite',
            name='son_hata_mesaji',
            field=models.TextField(blank=True, help_text='Son taramada alınan hata mesajı', null=True),
        ),
    ]
