# Generated by Django 5.2.7 on 2026-06-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0019_bekleyenhaber_kaynak_resim_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bekleyenhaber',
            name='resim',
            field=models.ImageField(blank=True, help_text='Manüel yüklenen veya değiştirilen görsel', null=True, upload_to='bekleyen_haberler/'),
        ),
        migrations.AddField(
            model_name='federasyonwebsite',
            name='logo',
            field=models.ImageField(blank=True, help_text='Federasyon logosu (haber resmi yoksa kullanılır)', null=True, upload_to='federasyon_logolari/'),
        ),
    ]
