# Generated by Django 5.2.7 on 2026-06-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0020_bekleyenhaber_resim_federasyonwebsite_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BultenAbone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eposta', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('kullanici_adi', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kullanıcı Adı')),
                ('isim', models.CharField(blank=True, max_length=100, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyisim')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
            options={
                'verbose_name': 'Bülten Abonesi',
                'verbose_name_plural': 'Bülten Aboneleri',
                'ordering': ['-kayit_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Reklam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField(default=1, verbose_name='Reklam Numarası / Sıra No')),
                ('baslik', models.CharField(max_length=200, verbose_name='Reklam Başlığı')),
                ('reklam_tipi', models.CharField(choices=[('bik_ihale', 'BİK Resmi İhale İlanı'), ('bik_duyuru', 'BİK Resmi Duyuru İlanı'), ('google_adsense', 'Google AdSense (JS Kodu)'), ('google_analytics', 'Google Analytics (JS Kodu)'), ('custom_banner', 'Özel Afiş/Görsel Reklam')], max_length=30, verbose_name='Reklam Tipi')),
                ('konum', models.CharField(choices=[('manset_4', 'Manşet Slider - 4. Sıra'), ('manset_8', 'Manşet Slider - 8. Sıra'), ('manset_12', 'Manşet Slider - 12. Sıra'), ('grid_5', 'Haber Izgarası - 5. Sıra'), ('grid_10', 'Haber Izgarası - 10. Sıra'), ('grid_15', 'Haber Izgarası - 15. Sıra'), ('grid_20', 'Haber Izgarası - 20. Sıra'), ('global_head', 'Global - HTML Head İçi'), ('global_body', 'Global - HTML Body Sonu')], max_length=30, verbose_name='Reklam Konumu')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='reklamlar/', verbose_name='Afiş/Görsel')),
                ('hedef_url', models.URLField(blank=True, null=True, verbose_name='Hedef URL Linki')),
                ('detaylar', models.TextField(blank=True, null=True, verbose_name='Reklam Detayları (BİK İlan Bilgileri vb.)')),
                ('kod', models.TextField(blank=True, null=True, verbose_name='AdSense/Analytics JS Kodu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
                'ordering': ['sira_no'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='yazarlar/', verbose_name='Profil Resmi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
    ]
