# Generated by Django 5.2.7 on 2026-06-24 04:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0021_bultenabone_reklam_userprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BekleyenSosyalMedyaHaberi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram 📸'), ('twitter', 'X / Twitter 🐦'), ('facebook', 'Facebook 👥')], max_length=20, verbose_name='Platform')),
                ('paylasim_id', models.CharField(max_length=100, unique=True, verbose_name='Gönderi Benzersiz ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık / Özet')),
                ('icerik', models.TextField(verbose_name='Gönderi Metni İçeriği')),
                ('kaynak_url', models.URLField(max_length=500, verbose_name='Gönderi Bağlantısı (URL)')),
                ('kaynak_resim_url', models.URLField(blank=True, max_length=600, null=True, verbose_name='Orijinal Resim URL')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='bekleyen_sosyal_medya/', verbose_name='Yerel Görsel')),
                ('paylasim_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Paylaşım Tarihi')),
                ('onaylandi', models.BooleanField(default=False, verbose_name='Onaylandı mı?')),
                ('reddedildi', models.BooleanField(default=False, verbose_name='Reddedildi mi?')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True)),
                ('federasyon_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.federasyonwebsite', verbose_name='Federasyon')),
                ('onaylayan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onaylanan_sosyal_gonderiler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bekleyen Sosyal Medya Haberi',
                'verbose_name_plural': 'Bekleyen Sosyal Medya Haberleri',
                'ordering': ['-paylasim_tarihi'],
            },
        ),
    ]
