# Generated by Django 5.2.7 on 2026-06-24 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0022_bekleyensosyalmedyahaberi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bekleyensosyalmedyahaberi',
            name='gonderi_tipi',
            field=models.CharField(choices=[('post', 'Fotoğraf/Gönderi 🖼️'), ('reel', 'Reel Video 🎥'), ('story', 'Hikaye/Story ⏳')], default='post', max_length=20, verbose_name='Gönderi Tipi'),
        ),
        migrations.CreateModel(
            name='FederasyonSosyalMedya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_kullanici_adi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Kullanıcı Adı')),
                ('facebook_sayfasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Sayfası/Kullanıcı Adı')),
                ('x_sayfasi', models.CharField(blank=True, max_length=100, null=True, verbose_name='X / Twitter Kullanıcı Adı')),
                ('federasyon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sosyal_medya', to='haberler.federasyonwebsite', verbose_name='Federasyon')),
            ],
            options={
                'verbose_name': 'Federasyon Sosyal Medya Hesabı',
                'verbose_name_plural': 'Federasyon Sosyal Medya Hesapları',
            },
        ),
    ]
