# Generated by Django 5.2.7 on 2026-06-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0023_bekleyensosyalmedyahaberi_gonderi_tipi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imtiyaz_sahibi', models.CharField(max_length=200, verbose_name='İmtiyaz Sahibi')),
                ('yazi_isleri_muduru', models.CharField(max_length=200, verbose_name='Yazı İşleri Müdürü')),
                ('tuzel_kisi_temsilcisi', models.CharField(max_length=200, verbose_name='Tüzel Kişi Temsilcisi')),
                ('editorler', models.TextField(help_text='Virgülle ayırarak yazabilirsiniz', verbose_name='Editörler')),
                ('yazilim_altyapi', models.CharField(max_length=200, verbose_name='Yazılım & Altyapı')),
                ('iletisim_adres', models.TextField(help_text='E-posta, telefon ve adres bilgileri', verbose_name='İletişim & Adres')),
                ('yer_saglayici', models.CharField(max_length=200, verbose_name='Yer Sağlayıcı')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Künye',
                'verbose_name_plural': 'Künye Bilgileri',
            },
        ),
        migrations.AlterField(
            model_name='bekleyenhaber',
            name='resim',
            field=models.FileField(blank=True, help_text='Manüel yüklenen veya değiştirilen görsel', null=True, upload_to='bekleyen_haberler/'),
        ),
        migrations.AlterField(
            model_name='bekleyensosyalmedyahaberi',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='bekleyen_sosyal_medya/', verbose_name='Yerel Görsel'),
        ),
        migrations.AlterField(
            model_name='bekleyenyetkilihaberi',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='bekleyen_haberler/'),
        ),
        migrations.AlterField(
            model_name='haber',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='haberler/'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='promosyonlar/', verbose_name='Afiş/Görsel'),
        ),
    ]
