# Generated by Django 5.2.7 on 2026-06-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0024_kunye_alter_bekleyenhaber_resim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklam',
            name='video',
            field=models.FileField(blank=True, help_text='Sadece .mp4, .webm formatları desteklenir. Otomatik döngü ve sessiz oynatılır.', null=True, upload_to='promosyonlar/videolar/', verbose_name='Video Dosyası'),
        ),
        migrations.AddField(
            model_name='reklam',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Örnek: https://www.youtube.com/watch?v=VIDEO_ID', null=True, verbose_name='YouTube Video Linki'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='konum',
            field=models.CharField(choices=[('manset_4', 'Manşet Slider - 4. Sıra'), ('manset_8', 'Manşet Slider - 8. Sıra'), ('manset_12', 'Manşet Slider - 12. Sıra'), ('grid_5', 'Haber Izgarası - 5. Sıra'), ('grid_10', 'Haber Izgarası - 10. Sıra'), ('grid_15', 'Haber Izgarası - 15. Sıra'), ('grid_20', 'Haber Izgarası - 20. Sıra'), ('global_head', 'Global - HTML Head İçi'), ('global_body', 'Global - HTML Body Sonu'), ('header_ad', 'Header - Logo Yanı Reklamı')], max_length=30, verbose_name='Reklam Konumu'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='reklam_tipi',
            field=models.CharField(choices=[('bik_ihale', 'BİK Resmi İhale İlanı'), ('bik_duyuru', 'BİK Resmi Duyuru İlanı'), ('google_adsense', 'Google AdSense (JS Kodu)'), ('google_analytics', 'Google Analytics (JS Kodu)'), ('custom_banner', 'Özel Afiş/Görsel Reklam'), ('video_file', 'Video Dosyası (MP4/WebM)'), ('youtube_loop', 'YouTube Video Döngüsü (Muted/Autoplay)')], max_length=30, verbose_name='Reklam Tipi'),
        ),
    ]
