# Generated by Django 5.2.7 on 2026-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0025_reklam_video_reklam_youtube_url_alter_reklam_konum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklam',
            name='iframe_url',
            field=models.URLField(blank=True, help_text='İframe içinde gösterilecek dış web sayfası adresi. Örnek: https://aysunkezbanant.com/', null=True, verbose_name='Dış Web Sayfası URL'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='reklam_tipi',
            field=models.CharField(choices=[('bik_ihale', 'BİK Resmi İhale İlanı'), ('bik_duyuru', 'BİK Resmi Duyuru İlanı'), ('google_adsense', 'Google AdSense (JS Kodu)'), ('google_analytics', 'Google Analytics (JS Kodu)'), ('custom_banner', 'Özel Afiş/Görsel Reklam'), ('video_file', 'Video Dosyası (MP4/WebM)'), ('youtube_loop', 'YouTube Video Döngüsü (Muted/Autoplay)'), ('iframe_page', 'Dış Web Sayfası (Iframe)')], max_length=30, verbose_name='Reklam Tipi'),
        ),
    ]
