# Generated by Django 5.2.7 on 2026-06-25 12:57

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('haberler', '0026_reklam_iframe_url_alter_reklam_reklam_tipi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazar',
            fields=[
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
