# Generated by Django 5.2.7 on 2026-07-16 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0027_yazar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konum', models.CharField(choices=[('slider_1', 'Slider 1. Kare'), ('slider_2', 'Slider 2. Kare'), ('slider_3', 'Slider 3. Kare'), ('slider_4', 'Slider 4. Kare'), ('slider_5', 'Slider 5. Kare'), ('slider_6', 'Slider 6. Kare'), ('slider_7', 'Slider 7. Kare'), ('slider_8', 'Slider 8. Kare'), ('slider_9', 'Slider 9. Kare'), ('slider_10', 'Slider 10. Kare'), ('kart_1', 'Haber Kartı 1. Kart'), ('kart_2', 'Haber Kartı 2. Kart'), ('kart_3', 'Haber Kartı 3. Kart'), ('kart_4', 'Haber Kartı 4. Kart'), ('kart_5', 'Haber Kartı 5. Kart'), ('kart_6', 'Haber Kartı 6. Kart'), ('kart_7', 'Haber Kartı 7. Kart'), ('kart_8', 'Haber Kartı 8. Kart'), ('kart_9', 'Haber Kartı 9. Kart'), ('kart_10', 'Haber Kartı 10. Kart'), ('kart_11', 'Haber Kartı 11. Kart'), ('kart_12', 'Haber Kartı 12. Kart'), ('kart_13', 'Haber Kartı 13. Kart'), ('kart_14', 'Haber Kartı 14. Kart'), ('kart_15', 'Haber Kartı 15. Kart'), ('kart_16', 'Haber Kartı 16. Kart'), ('kart_17', 'Haber Kartı 17. Kart'), ('kart_18', 'Haber Kartı 18. Kart'), ('header', 'Header Reklamı'), ('footer', 'Footer Reklamı')], max_length=20, unique=True, verbose_name='Reklam Konumu')),
                ('baslik', models.CharField(max_length=200, verbose_name='Reklam Başlığı')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='reklamlar/', verbose_name='Reklam Görseli')),
                ('hedef_url', models.URLField(blank=True, help_text='Tıklandığında yönlendirilecek web sayfası adresi', null=True, verbose_name="Hedef Web Sayfası URL'si")),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('iframe_goster', models.BooleanField(default=False, help_text="Aktif edildiğinde, görsel yerine hedef URL'deki web sitesi canlı olarak kartın içinde gösterilir.", verbose_name='Canlı Web Sitesi (Iframe) Olarak Göster?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Anket Sorusu')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Anket',
                'verbose_name_plural': 'Anketler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Yarışma Başlığı')),
                ('description', models.TextField(blank=True, verbose_name='Yarışma Açıklaması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Yarışma (Quiz)',
                'verbose_name_plural': 'Yarışmalar (Quizzes)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KoseYazari',
            fields=[
            ],
            options={
                'verbose_name': 'Köşe Yazarı',
                'verbose_name_plural': 'Köşe Yazarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('haberler.userprofile',),
        ),
        migrations.AlterModelOptions(
            name='kunye',
            options={'verbose_name': 'Künye', 'verbose_name_plural': 'Künyeler'},
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='adi_soyadi',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='biyografi',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='bolge',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='fotograf',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='kariyer',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='kusak',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='sira_no',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='verildigi_tarih',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='verildigi_yer',
        ),
        migrations.RemoveField(
            model_name='karateantrenor',
            name='vize_yili',
        ),
        migrations.RemoveField(
            model_name='kunye',
            name='guncelleme_tarihi',
        ),
        migrations.RemoveField(
            model_name='kunye',
            name='iletisim_adres',
        ),
        migrations.RemoveField(
            model_name='kunye',
            name='yazi_isleri_muduru',
        ),
        migrations.RemoveField(
            model_name='kunye',
            name='yazilim_altyapi',
        ),
        migrations.RemoveField(
            model_name='sporcu',
            name='iletisim',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='bekleyenhaber',
            name='kategori',
            field=models.ForeignKey(blank=True, help_text='Haberin ekleneceği kategori', null=True, on_delete=django.db.models.deletion.SET_NULL, to='haberler.kategori'),
        ),
        migrations.AddField(
            model_name='federasyonwebsite',
            name='facebook_url',
            field=models.URLField(blank=True, help_text="Facebook URL'si", null=True),
        ),
        migrations.AddField(
            model_name='federasyonwebsite',
            name='haber_resim_selector',
            field=models.CharField(blank=True, help_text='CSS selector for news detail image', max_length=200),
        ),
        migrations.AddField(
            model_name='federasyonwebsite',
            name='instagram_url',
            field=models.URLField(blank=True, help_text="Instagram URL'si", null=True),
        ),
        migrations.AddField(
            model_name='federasyonwebsite',
            name='x_url',
            field=models.URLField(blank=True, help_text="X / Twitter URL'si", null=True),
        ),
        migrations.AddField(
            model_name='federasyonwebsite',
            name='youtube_url',
            field=models.URLField(blank=True, help_text="YouTube URL'si", null=True),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='ad_soyad',
            field=models.CharField(default='', max_length=150, verbose_name='Ad Soyad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='kademe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Antrenörlük Kademesi'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='kulup',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bağlı Olduğu Kulüp'),
        ),
        migrations.AddField(
            model_name='karateantrenor',
            name='sehir',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='antrenorler', to='haberler.karatesehir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kunye',
            name='adres',
            field=models.TextField(blank=True, verbose_name='Yönetim Yeri / Adres'),
        ),
        migrations.AddField(
            model_name='kunye',
            name='eposta',
            field=models.CharField(blank=True, max_length=100, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='kunye',
            name='sorumlu_yazi_isleri_muduru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sorumlu Yazı İşleri Müdürü'),
        ),
        migrations.AddField(
            model_name='kunye',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='kunye',
            name='ticari_unvan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ticari Unvan'),
        ),
        migrations.AddField(
            model_name='kunye',
            name='uets',
            field=models.CharField(blank=True, max_length=200, verbose_name='UETS Adresi'),
        ),
        migrations.AddField(
            model_name='kunye',
            name='web_tasarim_bilgi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Web Tasarım ve Barındırma'),
        ),
        migrations.AddField(
            model_name='kunye',
            name='yayinci',
            field=models.CharField(blank=True, max_length=200, verbose_name='Yayıncı'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar / Durum'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='adres',
            field=models.TextField(blank=True, null=True, verbose_name='Posta Adresi'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='anne_adi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anne Adı'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='antrenor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='haberler.karateantrenor', verbose_name='Antrenörü'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='baba_adi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Baba Adı'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='cep_telefonu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cep Telefonu'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=10, null=True, verbose_name='Cinsiyeti'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Adresi'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='sporcu_fotolari/', verbose_name='Sporcu Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='il_ilce',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adres İl/İlçe'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='is_web_kayit',
            field=models.BooleanField(default=False, verbose_name='Yeni Kayıt (Web)'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='lisans_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lisans No'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='lisans_vize_yili',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Lisans Vize Yılı'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='sicil_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sicil No'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='sonraki_kemer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sonraki Kemer Hedefi'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='uyruk',
            field=models.CharField(default='T.C.', max_length=50, verbose_name='Uyruğu'),
        ),
        migrations.AddField(
            model_name='sporcu',
            name='yedek_telefon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diğer Tel No'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='anasayfa_yazari',
            field=models.BooleanField(default=False, verbose_name="Ana Sayfa Yazar Slider'ında Göster"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_column',
            field=models.BooleanField(default=True, verbose_name='Köşe Yazısı Yazma Yetkisi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_news',
            field=models.BooleanField(default=True, verbose_name='Haber Ekleme Yetkisi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_news',
            field=models.BooleanField(default=True, verbose_name='Kendi Haberlerini Düzenleme Yetkisi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_manage_comments',
            field=models.BooleanField(default=True, verbose_name='Yorum Yönetimi Yetkisi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profil_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='profil_resimleri/', verbose_name='Profil Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='bekleyenhaber',
            name='baslik',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bekleyenhaber',
            name='kaynak_url',
            field=models.URLField(help_text='Original source URL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bekleyenyetkilihaberi',
            name='baslik',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='haber',
            name='baslik',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='haber',
            name='kaynak_url',
            field=models.URLField(blank=True, help_text='Original source URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='haber',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='kunye',
            name='editorler',
            field=models.TextField(blank=True, help_text='Her satıra bir isim gelecek şekilde yazın', verbose_name='Editörler'),
        ),
        migrations.AlterField(
            model_name='kunye',
            name='imtiyaz_sahibi',
            field=models.CharField(blank=True, max_length=200, verbose_name='İmtiyaz Sahibi (Yayın Sahibi)'),
        ),
        migrations.AlterField(
            model_name='kunye',
            name='tuzel_kisi_temsilcisi',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tüzel Kişi Temsilcisi'),
        ),
        migrations.AlterField(
            model_name='kunye',
            name='yer_saglayici',
            field=models.CharField(blank=True, max_length=200, verbose_name='Yer Sağlayıcı'),
        ),
        migrations.AlterField(
            model_name='sporcu',
            name='kemer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mevcut Kuşağı'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Biyografi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='Konum'),
        ),
        migrations.CreateModel(
            name='KusakSinavBasvuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mevcut_kemer', models.CharField(max_length=50, verbose_name='Mevcut Kemer')),
                ('talep_edilen_kemer', models.CharField(max_length=50, verbose_name='Talep Edilen Kemer')),
                ('dekont', models.FileField(blank=True, null=True, upload_to='dekontlar/', verbose_name='Sınav Dekontu')),
                ('ucret_odendi', models.BooleanField(default=False, verbose_name='Ücret Yatırıldı mı?')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Sporcu Notu')),
                ('durum', models.CharField(choices=[('bekliyor', 'Onay Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi')], default='bekliyor', max_length=20, verbose_name='Başvuru Durumu')),
                ('basvuru_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('onay_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Onaylanma Tarihi')),
                ('sporcu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinav_basvurulari', to='haberler.sporcu', verbose_name='Sporcu')),
            ],
            options={
                'verbose_name': 'Kuşak Sınav Başvurusu',
                'verbose_name_plural': 'Kuşak Sınav Başvuruları',
                'ordering': ['-basvuru_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=255, verbose_name='Seçenek Metni')),
                ('votes_count', models.PositiveIntegerField(default=0, verbose_name='Oy Sayısı')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='haberler.poll', verbose_name='Anket')),
            ],
            options={
                'verbose_name': 'Anket Seçeneği',
                'verbose_name_plural': 'Anket Seçenekleri',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Soru Metni')),
                ('option_a', models.CharField(max_length=255, verbose_name='A Şıkkı')),
                ('option_b', models.CharField(max_length=255, verbose_name='B Şıkkı')),
                ('option_c', models.CharField(max_length=255, verbose_name='C Şıkkı')),
                ('option_d', models.CharField(max_length=255, verbose_name='D Şıkkı')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Doğru Cevap')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='haberler.quiz', verbose_name='Yarışma')),
            ],
            options={
                'verbose_name': 'Yarışma Sorusu',
                'verbose_name_plural': 'Yarışma Soruları',
            },
        ),
        migrations.CreateModel(
            name='TaramaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarama_zamani', models.DateTimeField(auto_now_add=True)),
                ('durum', models.CharField(choices=[('basarili', 'Başarılı'), ('hata', 'Hata')], max_length=20, verbose_name='Tarama Durumu')),
                ('eklenen_sayi', models.IntegerField(default=0, verbose_name='Eklenen Haber Sayısı')),
                ('mesaj', models.TextField(blank=True, null=True, verbose_name='Açıklama / Mesaj')),
                ('federasyon_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarama_loglari', to='haberler.federasyonwebsite')),
            ],
            options={
                'verbose_name': 'Tarama Logu',
                'verbose_name_plural': 'Tarama Logları',
                'ordering': ['-tarama_zamani'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='Alınan Puan')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Tamamlama Tarihi')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.quiz', verbose_name='Yarışma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Yarışma Skoru',
                'verbose_name_plural': 'Yarışma Skorları',
                'ordering': ['-score', 'completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oy Verme Zamanı')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.pollchoice', verbose_name='Seçenek')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haberler.poll', verbose_name='Anket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oy Veren Kullanıcı')),
            ],
            options={
                'verbose_name': 'Anket Oyu',
                'verbose_name_plural': 'Anket Oyları',
                'unique_together': {('poll', 'ip_address'), ('poll', 'user')},
            },
        ),
    ]
