# Generated by Django 5.2.8 on 2026-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0028_ad_poll_quiz_koseyazari_alter_kunye_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bekleyenhaber',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Haber bir video mu?'),
        ),
        migrations.AddField(
            model_name='bekleyenhaber',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL (Telegram CDN / Instagram)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='haber',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Haber bir video mu?'),
        ),
        migrations.AddField(
            model_name='haber',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video URL (Telegram CDN / Instagram)', max_length=1000, null=True),
        ),
    ]
